#!/bin/bash

# Phase 3 - File Addition Helper Script
# This script opens Xcode and provides instructions

echo "=========================================="
echo "OneFocus Phase 3 - File Addition Helper"
echo "=========================================="
echo ""
echo "This script will help you add the new Phase 3 files to Xcode."
echo ""
echo "Phase 3 includes:"
echo "  ✓ Settings screen with notifications"
echo "  ✓ Insights/Analytics with calendar heatmap"
echo "  ✓ WidgetKit extension (Small & Medium)"
echo "  ✓ Second habit flow integration"
echo "  ✓ Deep linking support"
echo ""
echo "Opening Xcode project..."
echo ""

# Open Xcode project
open /Users/sreedeepkesavms/conductor/workspaces/1habit/kolkata/OneFocus/OneFocus.xcodeproj

echo "Xcode should now be opening..."
echo ""
echo "Please follow the steps in SETUP_PHASE3.md to:"
echo "  1. Add new Swift files to the project"
echo "  2. Create Widget Extension target"
echo "  3. Configure App Groups"
echo "  4. Build and test"
echo ""
echo "Files to add:"
echo ""
echo "📁 Features/Settings/"
echo "  ├── ViewModels/SettingsViewModel.swift"
echo "  ├── Views/SettingsView.swift"
echo "  └── Components/SettingRow.swift"
echo ""
echo "📁 Features/Insights/"
echo "  ├── ViewModels/InsightsViewModel.swift"
echo "  ├── Views/InsightsView.swift"
echo "  ├── Components/CalendarHeatmap.swift"
echo "  └── Components/InsightStatCard.swift"
echo ""
echo "📁 Services/"
echo "  └── NotificationService.swift"
echo ""
echo "📁 Core/"
echo "  └── DeepLinkHandler.swift"
echo ""
echo "📁 Features/SecondHabit/Views/"
echo "  └── SecondHabitOnboardingFlow.swift"
echo ""
echo "📁 OneFocusWidget/ (Create new target first)"
echo "  ├── OneFocusWidget.swift"
echo "  ├── OneFocusWidgetBundle.swift"
echo "  └── Info.plist"
echo ""
echo "For detailed instructions, see:"
echo "  → SETUP_PHASE3.md"
echo "  → PHASE3_FILES.md"
echo ""
echo "=========================================="
